Repository developersIndia/website, pull requests merged in 2022-02, with the labels that each got.

#44 Update contributing guidelines with comprehensive details
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#58 Implement a very basic CI/CD pipeline to lint & format code
  .github/workflows/main.yml
  package.json
Labels: enhancement

#63 add @types/node as a dev dependency
  package-lock.json
  package.json
Labels: dependencies

#59 Implement Husky + lint-staged for pre-commit hooks
  package-lock.json
  package.json
Labels: enhancement, dependencies

#62 Add ESLint & Prettier configurations
  .eslintrc.json
  .gitignore
  .prettierrc
  package.json
Labels: enhancement

#66 Fix broken ESLint configurations in CI/CD pipeline
  package-lock.json
  package.json
Labels: bug

#72 Configure Stale bot
  .github/stale.yml
Labels: enhancement, help wanted, good first issue

#70 Added support for Tailwind CSS
  package-lock.json
  package.json
  postcss.config.js
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: dependencies

#76 Add `.eslintignore` & `.prettierignore`
  .eslintignore
  .prettierignore
Labels: enhancement

#80 Feature/simplified tsconfig.json
  src/pages/_app.tsx
  tsconfig.json
Labels: enhancement

#84 Changed `tsconfig.json` file as per #75 with reference to #80
  tsconfig.json
Labels: enhancement

#93 Update README with updated Discord links & development procedures
  README.md
Labels: documentation

#95 Update contributing guidelines with a clause asking users to add themselves to All Contributors list
  .github/CONTRIBUTING.md
Labels: documentation

#92 Add a draft `ROADMAP.md`
  ROADMAP.md
Labels: documentation, help wanted

#114 Updated README.md installation steps' cloning methods
  .all-contributorsrc
  README.md
  ROADMAP.md
Labels: documentation

#120 Add a standard for structuring React Components for the Project
  .github/CONTRIBUTING.md
  README.md
Labels: documentation
