Repository developersIndia/website, pull requests merged in 2022-03, with the labels that each got.

#129 Remove TailwindCSS & PostCSS configuration files
  README.md
  postcss.config.js
  src/styles/globals.css
  tailwind.config.js
Labels: dependencies

#132 Draft for the version management of the project
  .github/CONTRIBUTING.md
Labels: documentation, help wanted

#137 Configure project to use GitHub Actions for CI/CD & add NextUI to the project
  .github/workflows/main.yml
  .github/workflows/preview.yml
  .gitignore
  README.md
  netlify.toml
  package-lock.json
  package.json
Labels: enhancement, dependencies

#141 Setup NextUI & base theme to build upon later on
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/styles/theme.ts
Labels: enhancement, dependencies
